"use strict";
(function () {
  // ── Shared helpers (used by the picker and the Download menu) ──────────────
  // Snapshot the pristine template BEFORE any DOM mutation, so the HTML download
  // carries a clean shell with data swapped into the PARCEL-DATA markers.
  var TEMPLATE_HTML = "<!doctype html>\n" + document.documentElement.outerHTML;
  // PII allowlist (mirrors the old build_dashboard.py): keep every non-input_
  // column; of input_ keep only these five. The rest never reach a saved file.
  var KEEP_INPUT = { "input_ort":1, "input_plz":1, "input_rg":1, "input_bez. grundstück":1, "input_eigent.art":1, "input_tpf":1 };
  var keepKey = function (k) { return k.indexOf("input_") === 0 ? !!KEEP_INPUT[k] : true; };
  var DATA_MARKERS = /<!-- PARCEL-DATA:START[\s\S]*?PARCEL-DATA:END -->/;
  var jsonSafe = function (o) { return JSON.stringify(o).replace(/</g, "\\u003c"); };
  var slug = function (s) { return (String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")) || "landcover-dashboard"; };
  var saveBlob = function (data, type, name) {
    var a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([data], { type: type }));
    a.download = name; a.click();
    setTimeout(function () { URL.revokeObjectURL(a.href); }, 1000);
  };
  // SheetJS on demand for the Excel table export (Download menu). Needs internet.
  var _xlsxP = null;
  var loadXlsx = function () {
    if (window.XLSX) return Promise.resolve(window.XLSX);
    if (!_xlsxP) _xlsxP = new Promise(function (res, rej) {
      var s = document.createElement("script");
      s.src = "https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js";
      s.onload = function () { res(window.XLSX); };
      s.onerror = function () { _xlsxP = null; rej(new Error("SheetJS konnte nicht geladen werden (Internetverbindung nötig).")); };
      document.head.appendChild(s);
    });
    return _xlsxP;
  };
  // GeoJSON text → parcel rows. Multi-layer exports tag features with `layer`
  // (parcel/landcover/bauzonen/habitat); keep only parcel rows (they carry the
  // bauzonen/habitat aggregates). Legacy parcels-only exports have no `layer`.
  var readGeojsonParcels = function (text) {
    var props = ((JSON.parse(text) || {}).features || []).map(function (f) {
      var pr = (f && f.properties) || {};
      if (f && f.geometry) pr._geom = f.geometry; // kept for the map (not a PII field; survives the allowlist)
      return pr;
    });
    var total = props.length;
    if (props.some(function (p) { return "layer" in p; })) props = props.filter(function (p) { return p.layer === "parcel"; });
    props.forEach(function (p) { delete p.layer; });
    return { parcels: props, skipped: total - props.length };
  };
  // Strip non-allowlisted (PII) columns → { cleaned, dropped }.
  var allowlist = function (rows) {
    var droppedSet = {};
    var cleaned = rows.map(function (p) {
      var o = {};
      for (var k in p) { if (!Object.prototype.hasOwnProperty.call(p, k)) continue; if (keepKey(k)) o[k] = p[k]; else droppedSet[k] = 1; }
      return o;
    });
    return { cleaned: cleaned, dropped: Object.keys(droppedSet).sort() };
  };
  // Self-contained deliverable: clean template + embedded (allowlisted) parcels.
  var fetchText = function (url) {
    return fetch(url).then(function (r) { if (!r.ok) throw new Error("HTTP " + r.status + " für " + url); return r.text(); });
  };
  // Inline local <link rel=stylesheet> and <script src> so the saved file is
  // self-contained (same model as the web app's report export). CDN refs (https)
  // are left as-is. Needs http — fetch is blocked on file://. A saved deliverable
  // already has everything inline, so there is nothing to fetch (works offline).
  var inlineAssets = function (html) {
    var jobs = [], m;
    var add = function (tag, url, wrap) { jobs.push(fetchText(url).then(function (t) { return [tag, wrap(t)]; })); };
    var lre = /<link\b[^>]*rel=["']stylesheet["'][^>]*href=["'](?!https?:)([^"']+)["'][^>]*>/g;
    while ((m = lre.exec(html))) add(m[0], m[1], function (css) { return "<style>\n" + css + "\n</style>"; });
    var sre = /<script\b[^>]*src=["'](?!https?:)([^"']+)["'][^>]*><\/script>/g;
    while ((m = sre.exec(html))) add(m[0], m[1], function (js) { return "<script>\n" + js + "\n<\/script>"; });
    return Promise.all(jobs).then(function (pairs) {
      pairs.forEach(function (pr) { html = html.replace(pr[0], function () { return pr[1]; }); });
      return html;
    });
  };
  var buildDeliverable = function (parcels, title) {
    var data = "window.DASHBOARD_TITLE = " + jsonSafe(title || "BBL Landcover Dashboard") + ";\n" +
               "window.PARCELS = " + jsonSafe(parcels) + ";\n";
    var block = "<!-- PARCEL-DATA:START — generated by the in-browser builder; do not edit by hand -->\n" +
                "<script>\n" + data + "<\/script>\n" +
                "<!-- PARCEL-DATA:END -->";
    return inlineAssets(TEMPLATE_HTML).then(function (html) { return html.replace(DATA_MARKERS, function () { return block; }); });
  };

  // ── Picker: no embedded data → pick a file, allowlist, then render in place ──
  function initPicker() {
    document.body.classList.add("builder-mode"); // .builder-mode shows the picker, hides the dashboard
    var bEl = function (id) { return document.getElementById(id); };
    var fmtN = new Intl.NumberFormat("de-CH");
    var setStatus = function (h) { bEl("b-status").innerHTML = h; };
    var geo = null;
    bEl("b-geojson").addEventListener("change", function (e) {
      var f = e.target.files[0]; if (!f) return;
      setStatus("GeoJSON wird gelesen…");
      f.text().then(function (t) {
        try {
          geo = readGeojsonParcels(t);
          bEl("b-show").disabled = false;
          setStatus(fmtN.format(geo.parcels.length) + " Grundstücke aus GeoJSON geladen" + (geo.skipped ? " (" + fmtN.format(geo.skipped) + " Detail-Features übersprungen)" : "") + ".");
        } catch (err) { geo = null; bEl("b-show").disabled = true; setStatus("Fehler beim Lesen der GeoJSON: " + err.message); }
      });
    });
    bEl("b-show").addEventListener("click", function () {
      if (!geo) return;
      var clean = allowlist(geo.parcels).cleaned; // strip PII at import
      document.body.classList.remove("builder-mode"); // hide the picker, reveal the dashboard
      boot(clean);
    });
  }

  // German labels for BBArt land cover types
  var ART_LABELS = {
    Gebaeude:"Gebäude", Strasse_Weg:"Strasse/Weg", Trottoir:"Trottoir", Verkehrsinsel:"Verkehrsinsel",
    Bahn:"Bahn", Flugplatz:"Flugplatz", Wasserbecken:"Wasserbecken", uebrige_befestigte:"Übrige befestigte",
    Acker_Wiese_Weide:"Acker/Wiese/Weide", Reben:"Reben", uebrige_Intensivkultur:"Übrige Intensivkultur",
    Gartenanlage:"Gartenanlage", Hoch_Flachmoor:"Hoch-/Flachmoor", uebrige_humusierte:"Übrige humusierte",
    Wytweide_dicht:"Wytweide (dicht)", Wytweide_offen:"Wytweide (offen)", Gewaesser_stehendes:"Stehendes Gewässer",
    Gewaesser_fliessendes:"Fliessendes Gewässer", Schilfguertel:"Schilfgürtel", geschlossener_Wald:"Geschlossener Wald",
    uebrige_bestockte:"Übrige bestockte", Fels:"Fels", Gletscher_Firn:"Gletscher/Firn", Geroell_Sand:"Geröll/Sand",
    Abbau_Deponie:"Abbau/Deponie", uebrige_vegetationslose:"Übrige vegetationslose"
  };
  var ART_COLORS = {
    Gebaeude:"#c0392b", Strasse_Weg:"#7f8c8d", Trottoir:"#95a5a6", Verkehrsinsel:"#bdc3c7", Bahn:"#2c3e50",
    Flugplatz:"#34495e", Wasserbecken:"#3498db", uebrige_befestigte:"#9b59b6", Acker_Wiese_Weide:"#2ecc71",
    Reben:"#8e44ad", uebrige_Intensivkultur:"#1abc9c", Gartenanlage:"#27ae60", Hoch_Flachmoor:"#16a085",
    uebrige_humusierte:"#a3d977", Wytweide_dicht:"#82c341", Wytweide_offen:"#a8d08d", Gewaesser_stehendes:"#2980b9",
    Gewaesser_fliessendes:"#1f6faa", Schilfguertel:"#45b39d", geschlossener_Wald:"#1e8449", uebrige_bestockte:"#196f3d",
    Fels:"#aab7b8", Gletscher_Firn:"#d5dbdb", Geroell_Sand:"#d4ac0d", Abbau_Deponie:"#873600", uebrige_vegetationslose:"#b7950b"
  };
  // AV main category (Hauptgruppe) per BBArt type — DM.01-AV-CH, shown as a prefix
  // in the "Bodenbedeckung nach Art" chart to make the AV structure legible.
  var ART_MAIN = {
    Gebaeude:"Gebäude",
    Strasse_Weg:"Befestigt", Trottoir:"Befestigt", Verkehrsinsel:"Befestigt", Bahn:"Befestigt",
    Flugplatz:"Befestigt", Wasserbecken:"Befestigt", uebrige_befestigte:"Befestigt",
    Acker_Wiese_Weide:"Humusiert", Reben:"Humusiert", uebrige_Intensivkultur:"Humusiert",
    Gartenanlage:"Humusiert", Hoch_Flachmoor:"Humusiert", uebrige_humusierte:"Humusiert",
    Gewaesser_stehendes:"Gewässer", Gewaesser_fliessendes:"Gewässer", Schilfguertel:"Gewässer",
    geschlossener_Wald:"Bestockt", Wytweide_dicht:"Bestockt", Wytweide_offen:"Bestockt", uebrige_bestockte:"Bestockt",
    Fels:"Vegetationslos", Gletscher_Firn:"Vegetationslos", Geroell_Sand:"Vegetationslos",
    Abbau_Deponie:"Vegetationslos", uebrige_vegetationslose:"Vegetationslos"
  };
  // The 26 canonical BBArt land-cover types (allowlist for the "by type" chart),
  // derived from ART_LABELS so new aggregate columns in an export can never be
  // mistaken for a land-cover type.
  var ART_KEYS = Object.keys(ART_LABELS);
  // AV land-cover area column for a BBArt value: av_<art>_m2 (lowercase). The
  // ART_* maps stay keyed by the BBArt code (e.g. "Gebaeude"); only the geojson
  // column id is lowercased + av_-prefixed.
  function artCol(a) { return "av_" + String(a).toLowerCase() + "_m2"; }

  // EGRID resolution status (check_egrid). Default filter = only "found".
  var STATUS_LABELS = { found:"Gefunden", merged:"Gefunden (zusammengeführt)", not_found:"Nicht gefunden", invalid:"Ungültige EGRID", error:"Fehler" };
  var STATUS_ORDER = ["found", "merged", "not_found", "invalid", "error"];
  function statusKey(p) { var c = p.check_egrid || ""; return c.indexOf("error:") === 0 ? "error" : (c || "—"); }

  // "Name"/Bezeichnung column and prefix codes excluded by default (SAP categories
  // that are not real cadastral parcels for this analysis).
  var NAME_COL = "input_bez. grundstück";
  // mode "prefix" = Bezeichnung starts with the code; mode "word" = the code appears
  // as a standalone token anywhere (e.g. "Bern, Bollwerk 27, PP Miete"), avoiding
  // false hits inside words (Rapperswil, Appenzell, …).
  var EXCLUDE_RULES = [
    { key:"ABGA", label:"Abgang (ABGA*)", mode:"prefix" },
    { key:"LÖVM", label:"Löschvermerk (LÖVM*)", mode:"prefix" },
    { key:"PP",   label:"Parkplatz (*PP*)", mode:"word" }
  ];
  EXCLUDE_RULES.forEach(function (r) {
    var rawK = r.key.toUpperCase();
    if (r.mode === "word") {
      var escK = rawK.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      var rx = new RegExp("(^|[^A-Z0-9ÄÖÜ])" + escK + "([^A-Z0-9ÄÖÜ]|$)");
      r.test = function (name) { return rx.test(name); };
    } else {
      r.test = function (name) { return name.indexOf(rawK) === 0; };
    }
  });
  function defaultExclude() { var o = {}; EXCLUDE_RULES.forEach(function (r) { o[r.key] = true; }); return o; }
  function nameMatches(p, rule) {
    return rule.test(String(p[NAME_COL] == null ? "" : p[NAME_COL]).trim().toUpperCase());
  }

  var nf = new Intl.NumberFormat("de-CH");
  function num(v) { var n = parseFloat(v); return isFinite(n) ? n : 0; }
  function fmt(v) { return nf.format(Math.round(v)); }
  function ha(m2) { return m2 / 1e4; }
  function fmtHa(m2) { var h = ha(m2); return nf.format(h >= 100 ? Math.round(h) : Math.round(h*10)/10); }
  // ---- Area display unit (ha default / m²) — display only; the data stays m² ----
  var areaUnit = "ha";
  try { var _su = localStorage.getItem("dashAreaUnit"); if (_su === "ha" || _su === "m2") areaUnit = _su; } catch (e) { /* file:// may block storage */ }
  function unitLabel() { return areaUnit === "ha" ? "ha" : "m²"; }
  function fmtArea(m2) { return areaUnit === "m2" ? fmt(Math.round(num(m2))) : fmtHa(m2); }
  function fmtAreaU(m2) { return fmtArea(m2) + " " + unitLabel(); }
  function stripM2(s) { return String(s == null ? "" : s).replace(/\s*m²$/, ""); }
  function pct(part, whole) { return whole > 0 ? Math.round(part/whole*100) : 0; }
  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c]; }); }
  function isCovered(p) { return num(p.sia416_ggf_m2) + num(p.sia416_buf_m2) + num(p.sia416_uuf_m2) > 0; }


  function boot(PARCELS) {
  // ---- Precompute filter option counts (over the full dataset) ----
  var cantonCounts = {}, eigentumCounts = {}, artTotal = {}, artParcelCount = {}, covWith = 0, covWithout = 0;
  var excludeCounts = {}, statusCounts = {}, tpfCounts = {}, bauzoneTotal = {}, bauzoneParcelCount = {}, habitatTotal = {}, habitatParcelCount = {};
  var BAUZONE_RE = /^bauzonen_(.+)_m2$/; // bauzonen_<slug>_m2 (the bauzonen_m2 total does not match)
  // Display label per zone slug (ARE harmonised Hauptnutzung) — mirrors web/js/config.js.
  var BAUZONE_LABELS = {
    wohnzonen: "Wohnzonen", arbeitszonen: "Arbeitszonen", mischzonen: "Mischzonen",
    zentrumszonen: "Zentrumszonen", zonen_fuer_oeffentliche_nutzungen: "Zonen für öffentliche Nutzungen",
    eingeschraenkte_bauzonen: "eingeschränkte Bauzonen", tourismus_und_freizeitzonen: "Tourismus- und Freizeitzonen",
    verkehrszonen_innerhalb_der_bauzonen: "Verkehrszonen innerhalb der Bauzonen", weitere_bauzonen: "weitere Bauzonen"
  };
  function bzLabel(z) { return BAUZONE_LABELS[z] || String(z).replace(/_/g, " "); }
  var HABITAT_RE = /^habitat_(.+)_m2$/; // habitat_<slug>_m2 (the habitat_m2 total does not match)
  // Display label per habitat slug (TypoCH level-1) — mirrors web/js/config.js.
  var HABITAT_LABELS = {
    gewaesser: "Gewässer", ufer_feuchtgebiete: "Ufer & Feuchtgebiete",
    gletscher_fels_schutt_geroell: "Gletscher, Fels, Schutt, Geröll", gruenland: "Grünland",
    krautsaeume_hochstauden_gebuesche: "Krautsäume, Hochstauden, Gebüsche", waelder: "Wälder",
    pionier_ruderalvegetation: "Pionier-/Ruderalvegetation", pflanzungen_aecker_kulturen: "Pflanzungen, Äcker, Kulturen",
    gebaeude_anlagen: "Gebäude / Anlagen"
  };
  function hbLabel(h) { return HABITAT_LABELS[h] || String(h).replace(/_/g, " "); }
  EXCLUDE_RULES.forEach(function (r) { excludeCounts[r.key] = 0; });
  PARCELS.forEach(function (p) {
    var c = p.input_rg || ""; if (c) cantonCounts[c] = (cantonCounts[c] || 0) + 1;
    var e = p["input_eigent.art"] || ""; if (e) eigentumCounts[e] = (eigentumCounts[e] || 0) + 1;
    var tp = (p.input_tpf == null || p.input_tpf === "") ? "—" : String(p.input_tpf); tpfCounts[tp] = (tpfCounts[tp] || 0) + 1;
    var st = statusKey(p); statusCounts[st] = (statusCounts[st] || 0) + 1;
    if (isCovered(p)) covWith++; else covWithout++;
    EXCLUDE_RULES.forEach(function (r) { if (nameMatches(p, r)) excludeCounts[r.key]++; });
    ART_KEYS.forEach(function (a) {
      var v = num(p[artCol(a)]);
      if (v > 0) { artTotal[a] = (artTotal[a] || 0) + v; artParcelCount[a] = (artParcelCount[a] || 0) + 1; }
    });
    for (var bk in p) {
      var bm = BAUZONE_RE.exec(bk);
      if (bm) { var bv = num(p[bk]); if (bv > 0) { var bz = bm[1]; bauzoneTotal[bz] = (bauzoneTotal[bz] || 0) + bv; bauzoneParcelCount[bz] = (bauzoneParcelCount[bz] || 0) + 1; } }
      var hm = HABITAT_RE.exec(bk);
      if (hm) { var hv = num(p[bk]); if (hv > 0) { var hz = hm[1]; habitatTotal[hz] = (habitatTotal[hz] || 0) + hv; habitatParcelCount[hz] = (habitatParcelCount[hz] || 0) + 1; } }
    }
  });
  var cantonList = Object.keys(cantonCounts).sort(function (a, b) { return cantonCounts[b] - cantonCounts[a]; });
  var artListAll = Object.keys(artTotal).sort(function (a, b) { return artTotal[b] - artTotal[a]; });
  var bauzoneListAll = Object.keys(bauzoneTotal).sort(function (a, b) { return bauzoneTotal[b] - bauzoneTotal[a]; });
  var habitatListAll = Object.keys(habitatTotal).sort(function (a, b) { return habitatTotal[b] - habitatTotal[a]; });
  var tpfList = Object.keys(tpfCounts).sort(function (a, b) { return tpfCounts[b] - tpfCounts[a]; });
  var eigentumList = Object.keys(eigentumCounts).sort();
  var statusList = STATUS_ORDER.filter(function (s) { return statusCounts[s]; })
    .concat(Object.keys(statusCounts).filter(function (s) { return STATUS_ORDER.indexOf(s) === -1; }));

  // ---- Filter state ----
  // Defaults active on load: ABGA*/LÖVM*/PP* excluded, EGRID-Status "Gefunden",
  // and Eigentumsart 1 (Bodenbedeckung defaults to "Alle"). The empty URL
  // represents exactly this default state; query params encode deviations from it.
  // Aggregate "Enthält" categories (clickable on the SIA 416 / Grün·Versiegelung·VBS
  // charts). Like the per-Art filter, each selects Grundstücke that *contain* the
  // category (value > 0) — it does not hide the other land cover of those parcels.
  var HAS_METRICS = {
    GGF:    { label:"Gebäudegrundfläche (GGF)", field:"sia416_ggf_m2" },
    BUF:    { label:"Bearbeitete Umgebung (BUF)", field:"sia416_buf_m2" },
    UUF:    { label:"Unbearbeitete Umgebung (UUF)", field:"sia416_uuf_m2" },
    Green:  { label:"Grünfläche", field:"greenspace_m2" },
    Sealed: { label:"Versiegelte Fläche", field:"sealed_m2" },
    VBSp:   { label:"VBS produktiv", field:"vbs_produktiv_m2" },
    VBSu:   { label:"VBS unproduktiv", field:"vbs_unproduktiv_m2" }
  };
  var HAS_KEYS = Object.keys(HAS_METRICS);
  var hasCounts = {};
  HAS_KEYS.forEach(function (m) { hasCounts[m] = 0; });
  PARCELS.forEach(function (p) { HAS_KEYS.forEach(function (m) { if (num(p[HAS_METRICS[m].field]) > 0) hasCounts[m]++; }); });

  function defaultEigentum() { return eigentumCounts["1"] ? { "1": true } : {}; }
  function defaultStatus() { return statusCounts["found"] ? { found: true } : {}; }
  function defaultFilters() {
    return { cantons:{}, coverage:"all", arts:{}, has:{}, bauzonen:{}, tpf:{}, eigentum:defaultEigentum(), status:defaultStatus(), exclude:defaultExclude() };
  }
  var filters = defaultFilters();

  function passesFilters(p) {
    for (var i = 0; i < EXCLUDE_RULES.length; i++) {
      var r = EXCLUDE_RULES[i];
      if (filters.exclude[r.key] && nameMatches(p, r)) return false;
    }
    var st = Object.keys(filters.status);
    if (st.length && !filters.status[statusKey(p)]) return false;
    var cs = Object.keys(filters.cantons);
    if (cs.length && !filters.cantons[p.input_rg || ""]) return false;
    if (filters.coverage === "with" && !isCovered(p)) return false;
    if (filters.coverage === "without" && isCovered(p)) return false;
    var as = Object.keys(filters.arts);
    if (as.length && !as.some(function (a) { return num(p[artCol(a)]) > 0; })) return false;
    var bz = Object.keys(filters.bauzonen);
    if (bz.length && !bz.some(function (z) { return num(p["bauzonen_" + z + "_m2"]) > 0; })) return false;
    var hs = Object.keys(filters.has);
    if (hs.length && !hs.some(function (m) { return num(p[HAS_METRICS[m].field]) > 0; })) return false;
    var es = Object.keys(filters.eigentum);
    if (es.length && !filters.eigentum[p["input_eigent.art"] || ""]) return false;
    var tp = Object.keys(filters.tpf);
    if (tp.length && !filters.tpf[(p.input_tpf == null || p.input_tpf === "") ? "—" : String(p.input_tpf)]) return false;
    return true;
  }
  function activeGroups() {
    var n = 0;
    if (EXCLUDE_RULES.some(function (r) { return filters.exclude[r.key] && excludeCounts[r.key] > 0; })) n++;
    if (Object.keys(filters.cantons).length) n++;
    if (filters.coverage !== "all") n++;
    if (Object.keys(filters.arts).length) n++;
    if (Object.keys(filters.bauzonen).length) n++;
    if (Object.keys(filters.has).length) n++;
    if (Object.keys(filters.tpf).length) n++;
    if (Object.keys(filters.eigentum).length) n++;
    if (Object.keys(filters.status).length) n++;
    return n;
  }

  // ---- Table state & search ----
  var SEARCH_KEYS = ["id", "egrid", "nummer", "input_ort", "input_rg", "input_bez. grundstück"];
  var state = { sort:"parcel_area_m2", dir:-1, search:"", page:1, pageSize:25, rows:PARCELS.slice() };
  var selectedParcelId = null; // parcel highlighted on the map / selected in the table
  var printing = false;

  function getFiltered() {
    var q = state.search.trim().toLowerCase();
    return PARCELS.filter(function (p) {
      if (!passesFilters(p)) return false;
      if (q && !SEARCH_KEYS.some(function (k) { return String(p[k] == null ? "" : p[k]).toLowerCase().indexOf(q) !== -1; })) return false;
      return true;
    });
  }

  // ---- Aggregation over a dataset ----
  function aggregate(rows) {
    var t = { parcelArea:0, GGF:0, BUF:0, UUF:0, Sealed:0, Green:0, VBSp:0, VBSu:0, VBSa:0, VBSb:0, VBSc:0, VBSd:0 }, byArt = {}, byBauzone = {}, byHabitat = {}, withData = 0;
    var wfsIssues = 0, geomIssues = 0;
    rows.forEach(function (p) {
      t.parcelArea += num(p.parcel_area_m2);
      t.GGF += num(p.sia416_ggf_m2); t.BUF += num(p.sia416_buf_m2); t.UUF += num(p.sia416_uuf_m2);
      t.Sealed += num(p.sealed_m2); t.Green += num(p.greenspace_m2);
      t.VBSp += num(p.vbs_produktiv_m2); t.VBSu += num(p.vbs_unproduktiv_m2);
      t.VBSa += num(p.vbs_kat_a_m2); t.VBSb += num(p.vbs_kat_b_m2); t.VBSc += num(p.vbs_kat_c_m2); t.VBSd += num(p.vbs_kat_d_m2);
      if (isCovered(p)) withData++;
      if (p.check_wfs && p.check_wfs !== "ok") wfsIssues++;
      if (p.check_geom && p.check_geom !== "ok") geomIssues++;
      ART_KEYS.forEach(function (a) { var v = num(p[artCol(a)]); if (v) byArt[a] = (byArt[a] || 0) + v; });
      for (var zi = 0; zi < bauzoneListAll.length; zi++) { var zk = bauzoneListAll[zi], zv = num(p["bauzonen_" + zk + "_m2"]); if (zv) byBauzone[zk] = (byBauzone[zk] || 0) + zv; }
      for (var hi = 0; hi < habitatListAll.length; hi++) { var hk = habitatListAll[hi], hv2 = num(p["habitat_" + hk + "_m2"]); if (hv2) byHabitat[hk] = (byHabitat[hk] || 0) + hv2; }
    });
    return { len:rows.length, withData:withData, totals:t, byArt:byArt, byBauzone:byBauzone, byHabitat:byHabitat, classified:t.GGF + t.BUF + t.UUF,
             wfsIssues:wfsIssues, geomIssues:geomIssues };
  }

  // ---- Summary-table renderer (with an inline proportion bar per row) ----
  function renderValTable(elId, items, total, fmtVal, showTotal, valHeader, anteilHint) {
    var el = document.getElementById(elId); if (!el) return;
    if (!items.length) { el.innerHTML = '<div class="empty-note">Keine Daten</div>'; return; }
    var sum = items.reduce(function (s, it) { return s + it.value; }, 0);
    var maxVal = items.reduce(function (m, it) { return it.muted ? m : Math.max(m, it.value); }, 0) || 1;
    var body = items.map(function (it) {
      var cls = ((it.muted ? "muted-row " : "") + (it.key ? "clickable" : "") + (it.selected ? " selected" : "")).trim();
      var attr = it.key ? ' data-key="' + esc(it.key) + '"' : "";
      var tip = it.key ? ' data-tip="' + esc(it.name + " — anklicken zum Filtern") + '"' : "";
      var anteil = total ? pct(it.value, total) + " %" : "";
      var bar = it.muted ? "" : '<span class="sumbar"><i style="width:' + (it.value / maxVal * 100).toFixed(1) + '%"></i></span>';
      return '<tr class="' + cls + '"' + attr + tip + '><td>' + esc(it.name) + '</td>' +
             '<td class="bar-col">' + bar + '</td>' +
             '<td class="num">' + fmtVal(it.value) + '</td><td class="num">' + anteil + '</td></tr>';
    }).join("");
    var totalRow = showTotal ? '<tr class="total"><td>Total</td><td class="bar-col"></td><td class="num">' + fmtVal(sum) + '</td><td class="num">' + (total ? "100 %" : "") + '</td></tr>' : "";
    var anteilTh = "Anteil" + (anteilHint ? ' <span class="ftip" data-tip="' + esc(anteilHint) + '">ⓘ</span>' : "");
    el.innerHTML = '<table class="sumtbl"><thead><tr><th>Kategorie</th><th class="bar-col"></th><th class="num">' + (valHeader || "") +
                   '</th><th class="num">' + anteilTh + '</th></tr></thead><tbody>' + body + totalRow + '</tbody></table>';
  }

  // ---- Total parcel area grouped by an arbitrary field (Portfolio, Region) → bar items ----
  var BAR_COLOR = "#6f8aac"; // a single calm hue for the Portfolio/Region bars — color reserved for emphasis elsewhere
  function groupBarItems(rows, field, selMap, topN) {
    var map = {};
    rows.forEach(function (p) {
      var v = p[field]; var k = (v == null || v === "") ? "—" : String(v);
      map[k] = (map[k] || 0) + num(p.parcel_area_m2);
    });
    var keys = Object.keys(map).filter(function (k) { return map[k] > 0; }).sort(function (a, b) { return map[b] - map[a]; });
    var items = keys.slice(0, topN).map(function (k, i) {
      return { name: k, value: map[k], color: BAR_COLOR, key: (k === "—" ? null : k), selected: !!(selMap && selMap[k]) };
    });
    if (keys.length > topN) {
      var rest = keys.slice(topN).reduce(function (s, k) { return s + map[k]; }, 0);
      items.push({ name: "Übrige (" + (keys.length - topN) + ")", value: rest, color: "#cbd5e1" });
    }
    return items;
  }

  // ---- Render KPIs + charts + footer from an aggregate ----
  function renderDashboard(rows) {
    var a = aggregate(rows);
    var ofArea = function (v) { return pct(v, a.totals.parcelArea) + "% der Grundstücksfläche"; };
    var ofCover = function (v) { return pct(v, a.classified) + "% der Bodenbedeckung"; };
    var kpis = [
      { label:"Grundstücke", value:fmt(a.len), sub:fmt(a.withData) + " mit Bodenbedeckung (" + pct(a.withData, a.len) + "%)",
        tip:"Anzahl Grundstücke (Liegenschaften und SDR) in der aktuellen Auswahl. Davon " + fmt(a.withData) + " mit Bodenbedeckung. " +
            "Entspricht " + pct(a.len, PARCELS.length) + "% des Datensatzes (" + fmt(PARCELS.length) + " Grundstücke)." },
      { label:"Grundstücksfläche", value:fmtAreaU(a.totals.parcelArea), sub:fmt(a.len) + " Grundstücke",
        tip:"Summe der berechneten Grundstücksflächen (GSF) — 2D-Planfläche auf LV95 (EPSG:2056). " +
            "Klassifizierte Bodenbedeckung: " + fmtAreaU(a.classified) + " (" + ofArea(a.classified) + ")." },
      { label:"Grünfläche", value:fmtAreaU(a.totals.Green), sub:ofCover(a.totals.Green),
        tip:"Humusierte und bestockte Flächen gemäss Grünflächen-Klassifizierung. Aktuell " + ofCover(a.totals.Green) + " bzw. " + ofArea(a.totals.Green) + "." },
      { label:"Versiegelte Fläche", value:fmtAreaU(a.totals.Sealed), sub:ofCover(a.totals.Sealed),
        tip:"Gebäude und befestigte Flächen (versiegelt). Aktuell " + ofCover(a.totals.Sealed) + " bzw. " + ofArea(a.totals.Sealed) + "." },
      { label:"Gebäudegrundfläche (GGF)", value:fmtAreaU(a.totals.GGF), sub:ofCover(a.totals.GGF),
        tip:"Gebäudegrundfläche nach SIA 416 (GGF). Aktuell " + ofCover(a.totals.GGF) + " bzw. " + ofArea(a.totals.GGF) + "." }
    ];
    document.getElementById("kpis").innerHTML = kpis.map(function (k) {
      return '<div class="card"><div class="label tip-term" data-tip="' + esc(k.tip) + '">' + k.label + '</div>' +
             '<div class="value">' + k.value + '</div><div class="sub">' + k.sub + '</div></div>';
    }).join("");

    // Bodenbedeckung nach Art (top 12 + Übrige) as a summary table.
    var artItems = Object.keys(a.byArt).filter(function (k) { return a.byArt[k] > 0; }).map(function (k) {
      var label = ART_LABELS[k] || k, main = ART_MAIN[k] || "";
      return {
        name: (main && main !== label) ? main + " · " + label : label,
        value: a.byArt[k], color: ART_COLORS[k] || "#94a3b8", key: k, selected: !!filters.arts[k]
      };
    }).sort(function (x, y) { return y.value - x.value; });
    var artShown = artItems.slice(0, 12);
    if (artItems.length > 12) {
      var artRest = artItems.slice(12).reduce(function (s, it) { return s + it.value; }, 0);
      artShown.push({ name: "Übrige (" + (artItems.length - 12) + ")", value: artRest, color: "#cbd5e1" });
    }
    var gsfHint = "Anteil an der gesamten Grundstücksfläche (GSF) der Auswahl.";
    var pa = a.totals.parcelArea;
    // Append a muted "remainder" row so each table sums to 100 % of the Grundstücksfläche;
    // the gap = parcel area the categories don't cover (z. B. ohne Bodenbedeckungsdaten).
    function withMiss(items, label) {
      var s = 0; items.forEach(function (it) { s += it.value; });
      var m = pa - s;
      return m > 0 ? items.concat([{ name: label || "Ohne Bodenbedeckung", value: m, muted: true }]) : items;
    }
    renderValTable("tbl-art", withMiss(artShown), pa, fmtArea, true, unitLabel(), gsfHint);
    renderValTable("tbl-sia", withMiss([
      { name:"GGF · Gebäudegrundfläche", value:a.totals.GGF, key:"GGF", selected:!!filters.has.GGF },
      { name:"BUF · bearbeitete Umgebung", value:a.totals.BUF, key:"BUF", selected:!!filters.has.BUF },
      { name:"UUF · unbearbeitete Umgebung", value:a.totals.UUF, key:"UUF", selected:!!filters.has.UUF }
    ]), pa, fmtArea, true, unitLabel(), gsfHint);
    // "Versiegelung" as the binary AV imperviousness view (CLASSIFICATION.md): versiegelt ja/nein.
    // Versiegelt = Gebäude + befestigt; Unversiegelt = übrige klassifizierte Bodenbedeckung.
    renderValTable("tbl-gsv", withMiss([
      { name:"Versiegelt", value:a.totals.Sealed, key:"Sealed", selected:!!filters.has.Sealed },
      { name:"Unversiegelt", value:Math.max(0, a.classified - a.totals.Sealed) }
    ]), pa, fmtArea, true, unitLabel(), gsfHint);
    renderValTable("tbl-vbs", withMiss([
      { name:"A · Siedlungsfläche", value:a.totals.VBSa },
      { name:"B · Landwirtschaftsfläche", value:a.totals.VBSb },
      { name:"C · Bestockte Fläche", value:a.totals.VBSc },
      { name:"D · Unproduktive Fläche", value:a.totals.VBSd }
    ]), pa, fmtArea, true, unitLabel(), gsfHint);
    renderValTable("tbl-vbsprod", withMiss([
      { name:"VBS produktiv", value:a.totals.VBSp },
      { name:"VBS unproduktiv", value:a.totals.VBSu }
    ]), pa, fmtArea, true, unitLabel(), gsfHint);
    var bzItems = bauzoneListAll.map(function (z) { return { name: bzLabel(z), value: a.byBauzone[z] || 0, key: z, selected: !!filters.bauzonen[z] }; })
      .filter(function (it) { return it.value > 0; }).sort(function (x, y) { return y.value - x.value; });
    var bzShown = bzItems.slice(0, 10);
    if (bzItems.length > 10) { var bzRest = bzItems.slice(10).reduce(function (s, it) { return s + it.value; }, 0); bzShown.push({ name: "Übrige (" + (bzItems.length - 10) + ")", value: bzRest }); }
    renderValTable("tbl-bauzonen", withMiss(bzShown, "Ausserhalb Bauzonen"), pa, fmtArea, true, unitLabel(), gsfHint);
    if (habitatListAll.length) {
      var hbItems = habitatListAll.map(function (h) { return { name: hbLabel(h), value: a.byHabitat[h] || 0 }; })
        .filter(function (it) { return it.value > 0; }).sort(function (x, y) { return y.value - x.value; });
      renderValTable("tbl-habitat", withMiss(hbItems, "Ohne Lebensraum-Daten"), pa, fmtArea, true, unitLabel(), gsfHint);
    }
    renderValTable("tbl-tpf", groupBarItems(rows, "input_tpf", filters.tpf, 12), a.totals.parcelArea, fmtArea, true, unitLabel(), gsfHint);
    renderValTable("tbl-rg", groupBarItems(rows, "input_rg", filters.cantons, 12), a.totals.parcelArea, fmtArea, true, unitLabel(), gsfHint);

    var qa = "";
    if (a.wfsIssues || a.geomIssues) {
      var parts = [];
      if (a.wfsIssues) parts.push(fmt(a.wfsIssues) + " mit WFS-Hinweis");
      if (a.geomIssues) parts.push(fmt(a.geomIssues) + " mit Geometrie-Hinweis");
      qa = "Datenqualität: " + parts.join(", ") + ". ";
    }
    document.getElementById("footer-note").innerHTML =
      "Anteile = % der klassifizierten Bodenbedeckung (" + fmtAreaU(a.classified) + "). " +
      fmt(a.len - a.withData) + " Grundstücke ohne Bodenbedeckung. " + qa;
  }

  // ---- Datenqualität tab (uses the existing check_* / status columns) ----
  function renderQuality(rows) {
    if (!document.getElementById("q-kpis")) return;
    var c = { found:0, merged:0, not_found:0, invalid:0, error:0 }, withCov = 0, woCov = 0, wfsIssue = 0, geomIssue = 0;
    var problems = [];
    rows.forEach(function (p) {
      var sk = statusKey(p); if (c[sk] != null) c[sk]++;
      var cov = isCovered(p); if (cov) withCov++; else woCov++;
      var wfs = p.check_wfs && p.check_wfs !== "ok"; if (wfs) wfsIssue++;
      var geom = p.check_geom && p.check_geom !== "ok"; if (geom) geomIssue++;
      var hint = "";
      if (sk === "not_found") hint = "EGRID nicht gefunden";
      else if (sk === "invalid") hint = "Ungültige EGRID";
      else if (sk === "error") hint = "Fehler";
      else if (!cov) hint = "0 m² Bodenbedeckung (kein WFS)";
      else if (geom) hint = "Geometrie-Hinweis";
      else if (wfs) hint = "WFS-Hinweis";
      if (hint) problems.push({ p: p, hint: hint });
    });
    var total = rows.length || 1, foundAll = c.found + c.merged;
    var qk = [
      { label:"EGRID aufgelöst", value:fmt(foundAll) + " / " + fmt(rows.length), sub:(c.merged ? fmt(c.merged) + " zusammengeführt" : "von der Auswahl") },
      { label:"Ohne Bodenbedeckung", value:fmt(woCov), sub:pct(woCov, total) + "% der Auswahl" },
      { label:"Geometrie-Hinweise", value:fmt(geomIssue), sub:fmt(wfsIssue) + " WFS-Hinweise" }
    ];
    document.getElementById("q-kpis").innerHTML = qk.map(function (k) {
      return '<div class="card"><div class="label">' + esc(k.label) + '</div><div class="value">' + k.value + '</div><div class="sub">' + esc(k.sub) + '</div></div>';
    }).join("");
    renderValTable("q-egrid", [
      { name:"Gefunden", value:c.found }, { name:"Zusammengeführt", value:c.merged },
      { name:"Nicht gefunden", value:c.not_found }, { name:"Ungültige EGRID", value:c.invalid }, { name:"Fehler", value:c.error }
    ].filter(function (it) { return it.value > 0; }), rows.length, fmt, true, "Anzahl", "Anteil an der Auswahl (Anzahl Grundstücke).");
    renderValTable("q-wfs", [
      { name:"mit Bodenbedeckung", value:withCov }, { name:"ohne (0 m² / kein WFS)", value:woCov }
    ], rows.length, fmt, true, "Anzahl", "Anteil an der Auswahl (Anzahl Grundstücke).");
    document.getElementById("q-count").textContent = fmt(problems.length) + (problems.length === 1 ? " Grundstück" : " Grundstücke");
    document.getElementById("q-tbody").innerHTML = problems.length
      ? problems.slice(0, 500).map(function (x) {
          var p = x.p;
          return "<tr><td>" + esc(p.id || "") + "</td><td>" + (p.egrid ? esc(p.egrid) : '<span class="muted">–</span>') +
                 "</td><td>" + esc(p.input_ort || "") + "</td><td>" + esc(x.hint) + "</td></tr>";
        }).join("")
      : '<tr><td colspan="4" class="empty">Keine Auffälligkeiten in der Auswahl.</td></tr>';
  }

  // ---- Table ----
  var COLUMNS = [
    { key:"id", label:"ID", def:true, tip:"Objektschlüssel BuKr/WE/Grundstk aus SAP." },
    { key:"egrid", label:"E-GRID", def:true, tip:"Eidgenössischer Grundstücksidentifikator (14-stellig). Klick öffnet das Grundstück auf map.geo.admin.ch.",
      render: function (v) {
        if (!v) return '<span class="muted">–</span>';
        var u = "https://map.geo.admin.ch/#/map?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe" +
                "&layers=ch.swisstopo-vd.stand-oerebkataster&swisssearch=" + encodeURIComponent(v);
        return '<a class="egrid-link" href="' + u + '" target="_blank" rel="noopener" data-tip="Grundstück auf map.geo.admin.ch öffnen (ÖREB-Kataster, neuer Tab)">' + esc(v) + " ↗</a>";
      } },
    { key:"nummer", label:"Grundstück-Nr.", def:false, tip:"Offizielle Grundstücknummer aus der amtlichen Vermessung." },
    { key:"input_ort", label:"Ort", def:true, tip:"Standortgemeinde des Grundstücks." },
    { key:"input_plz", label:"PLZ", def:false, tip:"Postleitzahl." },
    { key:"input_rg", label:"Kanton", def:true, tip:"Kanton (Region)." },
    { key:"input_bez. grundstück", label:"Bezeichnung", def:true, tip:"Bezeichnung des Grundstücks aus SAP." },
    { key:"input_eigent.art", label:"Eigentumsart", def:false, tip:"Eigentumsart-Code aus SAP (1/3/5)." },
    { key:"input_tpf", label:"Portfolio", def:false, tip:"Portfolio-Code (input_tpf) aus SAP. Klartext-Labels folgen." },
    { key:"check_egrid", label:"Status", def:false, tip:"EGRID-Status (gefunden / zusammengeführt / nicht gefunden)." },
    { key:"parcel_area_m2", label:"Grundstücksfläche m²", num:true, def:true, tip:"Berechnete Grundstücksfläche (GSF) — 2D-Planfläche auf LV95." },
    { key:"sia416_ggf_m2", label:"GGF m²", num:true, def:true, tip:"Gebäudegrundfläche nach SIA 416." },
    { key:"sia416_buf_m2", label:"BUF m²", num:true, def:false, tip:"Bearbeitete Umgebungsfläche nach SIA 416 (befestigt + humusiert)." },
    { key:"sia416_uuf_m2", label:"UUF m²", num:true, def:false, tip:"Unbearbeitete Umgebungsfläche nach SIA 416 (Gewässer + bestockt + vegetationslos)." },
    { key:"greenspace_m2", label:"Grünfläche m²", num:true, def:true, tip:"Grünfläche (humusiert + bestockt)." },
    { key:"sealed_m2", label:"Versiegelt m²", num:true, def:true, tip:"Versiegelte Fläche (Gebäude + befestigt)." },
    { key:"vbs_produktiv_m2", label:"VBS produktiv m²", num:true, def:false, tip:"Biologisch produktive Fläche (VBS-Klassifizierung)." },
    { key:"vbs_unproduktiv_m2", label:"VBS unproduktiv m²", num:true, def:false, tip:"Biologisch unproduktive Fläche (VBS-Klassifizierung)." }
  ];
  var colByKey = {};
  COLUMNS.forEach(function (c) { colByKey[c.key] = c; c.visible = c.def; });

  function sortRows() {
    var key = state.sort, dir = state.dir, isNum = colByKey[key] && colByKey[key].num;
    state.rows.sort(function (a, b) {
      var x = a[key], y = b[key];
      if (isNum) { return (num(x) - num(y)) * dir; }
      x = String(x == null ? "" : x); y = String(y == null ? "" : y);
      return x.localeCompare(y, "de") * dir;
    });
  }
  function renderHead() {
    var vis = COLUMNS.filter(function (c) { return c.visible; });
    document.getElementById("thead-row").innerHTML = vis.map(function (c) {
      var sorted = state.sort === c.key;
      var arrow = sorted ? ' <span class="arrow">' + (state.dir < 0 ? "▼" : "▲") + "</span>" : "";
      var tip = c.tip ? ' data-tip="' + esc(c.tip) + '"' : "";
      var cls = (c.num ? "num" : "") + (sorted ? " sorted" : "");
      var lbl = c.num ? stripM2(c.label) + " (" + unitLabel() + ")" : c.label;
      return '<th class="' + cls + '" data-key="' + esc(c.key) + '"' + tip + ">" + esc(lbl) + arrow + "</th>";
    }).join("");
  }
  function renderBody() {
    var vis = COLUMNS.filter(function (c) { return c.visible; });
    if (!state.rows.length) {
      document.getElementById("tbody").innerHTML = '<tr><td class="empty" colspan="' + vis.length + '">Keine Grundstücke entsprechen den Filtern.</td></tr>';
      return;
    }
    var start = (state.page - 1) * state.pageSize;
    var pageRows = printing ? state.rows : state.rows.slice(start, start + state.pageSize);
    document.getElementById("tbody").innerHTML = pageRows.map(function (p) {
      var pid = (p.id == null ? "" : String(p.id));
      var sel = (selectedParcelId && pid === selectedParcelId) ? ' class="row-selected"' : "";
      return '<tr data-id="' + esc(pid) + '"' + sel + ">" + vis.map(function (c) {
        var v = p[c.key];
        if (c.num) return '<td class="num">' + (num(v) ? fmtArea(num(v)) : '<span class="muted">0</span>') + "</td>";
        if (c.render) return "<td>" + c.render(v == null ? "" : String(v), p) + "</td>";
        var s = (v == null || v === "") ? "" : String(v);
        return "<td" + (s ? "" : ' class="muted"') + ">" + (s ? esc(s) : "–") + "</td>";
      }).join("") + "</tr>";
    }).join("");
  }
  function renderPager() {
    var total = state.rows.length, pages = Math.max(1, Math.ceil(total / state.pageSize));
    if (state.page > pages) state.page = pages;
    document.getElementById("page-info").textContent = "Seite " + state.page + " von " + pages;
    document.getElementById("prev").disabled = state.page <= 1;
    document.getElementById("next").disabled = state.page >= pages;
    document.getElementById("row-count").textContent =
      fmt(total) + " von " + fmt(PARCELS.length) + " Grundstücken" + (total < PARCELS.length ? " (gefiltert)" : "");
  }
  function renderFoot() {
    var vis = COLUMNS.filter(function (c) { return c.visible; });
    var sums = {};
    vis.forEach(function (c) { if (c.num) sums[c.key] = 0; });
    state.rows.forEach(function (p) { vis.forEach(function (c) { if (c.num) sums[c.key] += num(p[c.key]); }); });
    var labelDone = false;
    document.getElementById("tfoot-row").innerHTML = vis.map(function (c) {
      if (c.num) return '<td class="num">' + fmtArea(sums[c.key]) + "</td>";
      if (!labelDone) { labelDone = true; return "<td>Total · " + fmt(state.rows.length) + " Grundstücke</td>"; }
      return "<td></td>";
    }).join("");
  }
  function renderTable() { renderHead(); renderBody(); renderFoot(); renderPager(); }

  // Select a parcel from the map: highlight its polygon, page to it, scroll the row into view.
  function selectParcel(id) {
    selectedParcelId = (id == null || id === "") ? null : String(id);
    if (map && mapReady && map.getLayer("parcels-hl")) {
      map.setFilter("parcels-hl", ["==", ["get", "id"], selectedParcelId || " "]);
    }
    if (!selectedParcelId) { renderBody(); return; }
    var idx = -1;
    for (var i = 0; i < state.rows.length; i++) {
      if (String(state.rows[i].id == null ? "" : state.rows[i].id) === selectedParcelId) { idx = i; break; }
    }
    if (idx < 0) { renderBody(); return; } // parcel is filtered out of the current table
    var page = Math.floor(idx / state.pageSize) + 1;
    if (page !== state.page) { state.page = page; renderPager(); }
    renderBody();
    var tb = document.getElementById("tbody"), rows = tb ? tb.children : [];
    for (var j = 0; j < rows.length; j++) {
      if (rows[j].getAttribute && rows[j].getAttribute("data-id") === selectedParcelId) {
        if (rows[j].scrollIntoView) rows[j].scrollIntoView({ block: "center", behavior: "smooth" });
        break;
      }
    }
  }

  // ---- Central update: filter → recompute everything ----
  function update() {
    var rows = getFiltered();
    state.rows = rows;
    sortRows();
    state.page = 1;
    renderDashboard(rows);
    renderQuality(rows);
    renderTable();
    renderMap(rows);
    var n = activeGroups(), b = document.getElementById("filter-badge");
    if (b) { b.textContent = n; b.classList.toggle("show", n > 0); }
    var filtered = rows.length < PARCELS.length;
    var fk = document.getElementById("flag-kpi"); if (fk) fk.classList.toggle("show", filtered);
    var fq = document.getElementById("flag-q"); if (fq) fq.classList.toggle("show", filtered);
    var fc = document.getElementById("f-count"); if (fc) fc.textContent = fmt(rows.length) + " Grundstücke";
    renderPills();
  }
  function commit() { refitMap = true; writeURL(); update(); }

  // ---- Active-filter pills ----
  var _pillActions = [];
  function buildPills() {
    var pills = [];
    if (state.search.trim()) {
      pills.push({ label: 'Suche: "' + state.search.trim() + '"', remove: function () { state.search = ""; document.getElementById("search").value = ""; } });
    }
    EXCLUDE_RULES.forEach(function (r) {
      if (filters.exclude[r.key] && excludeCounts[r.key] > 0)
        pills.push({ label: "Ohne: " + r.label, remove: function () { delete filters.exclude[r.key]; } });
    });
    Object.keys(filters.cantons).forEach(function (c) {
      pills.push({ label: "Kanton: " + c, remove: function () { delete filters.cantons[c]; } });
    });
    if (filters.coverage === "with") pills.push({ label: "Nur mit Bodenbedeckung", remove: function () { filters.coverage = "all"; } });
    if (filters.coverage === "without") pills.push({ label: "Nur ohne Bodenbedeckung", remove: function () { filters.coverage = "all"; } });
    Object.keys(filters.arts).forEach(function (a) {
      pills.push({ label: "Enthält: " + (ART_LABELS[a] || a), remove: function () { delete filters.arts[a]; } });
    });
    Object.keys(filters.bauzonen).forEach(function (z) {
      pills.push({ label: "Bauzone: " + bzLabel(z), remove: function () { delete filters.bauzonen[z]; } });
    });
    Object.keys(filters.has).forEach(function (m) {
      pills.push({ label: "Enthält: " + HAS_METRICS[m].label, remove: function () { delete filters.has[m]; } });
    });
    Object.keys(filters.tpf).forEach(function (t) {
      pills.push({ label: "Portfolio: " + t, remove: function () { delete filters.tpf[t]; } });
    });
    Object.keys(filters.eigentum).forEach(function (e) {
      pills.push({ label: "Eigentumsart " + e, remove: function () { delete filters.eigentum[e]; } });
    });
    Object.keys(filters.status).forEach(function (s) {
      pills.push({ label: "Status: " + (STATUS_LABELS[s] || s), remove: function () { delete filters.status[s]; } });
    });
    return pills;
  }
  function renderPills() {
    _pillActions = buildPills();
    var row = document.getElementById("pill-row");
    if (!_pillActions.length) { row.innerHTML = ""; row.style.display = "none"; return; }
    row.style.display = "flex";
    row.innerHTML = _pillActions.map(function (p, i) {
      return '<span class="pill">' + esc(p.label) + '<button class="pill-x" data-i="' + i + '" aria-label="Filter entfernen">✕</button></span>';
    }).join("") + '<button class="pill-reset" id="pill-reset">Alle Filter zurücksetzen</button>';
  }

  // ---- Reset & drawer sync ----
  function resetAll() {
    filters = defaultFilters();
    state.search = ""; document.getElementById("search").value = "";
    syncDrawer(); commit();
  }
  function syncDrawer() {
    renderExclude(); renderStatus(); renderCantons(); renderArts(); renderBauzonen(); renderTpf(); renderEigentum();
    var cov = document.querySelector('#f-coverage input[value="' + filters.coverage + '"]');
    if (cov) cov.checked = true;
  }

  // ---- URL <-> filter state ----
  // Explicit model: every active filter is its own URL parameter; removing a
  // filter drops its parameter. A URL with no filter params means "no filters";
  // a completely empty URL (first visit) applies the defaults and stamps them in.
  var URL_KEYS = ["q", "excl", "status", "eig", "cov", "kanton", "art", "bauz", "has", "tpf"];
  function writeURL() {
    var pr = new URLSearchParams();
    if (state.search.trim()) pr.set("q", state.search.trim());
    var excl = EXCLUDE_RULES.filter(function (r) { return filters.exclude[r.key]; }).map(function (r) { return r.key; });
    if (excl.length) pr.set("excl", excl.join(","));
    var st = Object.keys(filters.status); if (st.length) pr.set("status", st.join(","));
    var eig = Object.keys(filters.eigentum); if (eig.length) pr.set("eig", eig.join(","));
    if (filters.coverage !== "all") pr.set("cov", filters.coverage);
    var cant = Object.keys(filters.cantons); if (cant.length) pr.set("kanton", cant.join(","));
    var art = Object.keys(filters.arts); if (art.length) pr.set("art", art.join(","));
    var bauz = Object.keys(filters.bauzonen); if (bauz.length) pr.set("bauz", bauz.join(","));
    var has = Object.keys(filters.has); if (has.length) pr.set("has", has.join(","));
    var tpf = Object.keys(filters.tpf); if (tpf.length) pr.set("tpf", tpf.join(","));
    var qs = pr.toString();
    try { history.replaceState(null, "", qs ? "?" + qs : location.pathname); } catch (e) { /* file:// may block */ }
  }
  // Returns true if defaults were applied (empty URL) and should be written back.
  function readURL() {
    var pr = new URLSearchParams(location.search);
    if (!URL_KEYS.some(function (k) { return pr.has(k); })) {
      filters = defaultFilters(); state.search = ""; document.getElementById("search").value = ""; return true;
    }
    var validExcl = defaultExclude();
    state.search = pr.get("q") || "";
    document.getElementById("search").value = state.search;
    filters.exclude = {}; (pr.get("excl") || "").split(",").forEach(function (k) { if (k && validExcl[k]) filters.exclude[k] = true; });
    filters.status = {}; (pr.get("status") || "").split(",").forEach(function (s) { if (s) filters.status[s] = true; });
    filters.eigentum = {}; (pr.get("eig") || "").split(",").forEach(function (e) { if (e) filters.eigentum[e] = true; });
    var cov = pr.get("cov"); filters.coverage = (cov === "with" || cov === "without") ? cov : "all";
    filters.cantons = {}; (pr.get("kanton") || "").split(",").forEach(function (c) { if (c) filters.cantons[c] = true; });
    filters.arts = {}; (pr.get("art") || "").split(",").forEach(function (a) { if (a) filters.arts[a] = true; });
    filters.bauzonen = {}; (pr.get("bauz") || "").split(",").forEach(function (z) { if (z) filters.bauzonen[z] = true; });
    filters.has = {}; (pr.get("has") || "").split(",").forEach(function (m) { if (m && HAS_METRICS[m]) filters.has[m] = true; });
    filters.tpf = {}; (pr.get("tpf") || "").split(",").forEach(function (t) { if (t) filters.tpf[t] = true; });
    return false;
  }

  // ---- Chart click → toggle the matching "Enthält" filter; pill click → remove/reset ----
  function chartToggle(elId, facet) {
    document.getElementById(elId).addEventListener("click", function (e) {
      var row = e.target.closest("[data-key]"); if (!row) return;
      var k = row.getAttribute("data-key");
      if (filters[facet][k]) delete filters[facet][k]; else filters[facet][k] = true;
      syncDrawer(); commit();
    });
  }
  chartToggle("tbl-art", "arts");        // per-Art types (summary-table rows)
  chartToggle("tbl-sia", "has");         // GGF / BUF / UUF
  chartToggle("tbl-gsv", "has");         // Grünfläche / Versiegelt
  chartToggle("tbl-bauzonen", "bauzonen"); // ARE-Bauzonentypen
  chartToggle("tbl-tpf", "tpf");         // Portfolio (input_tpf)
  chartToggle("tbl-rg", "cantons");      // Region (input_rg → Kanton-Filter)
  // BAFU Lebensräume: no per-type aggregation in the export yet — static placeholder.
  var habEl = document.getElementById("tbl-habitat");
  if (habEl) habEl.innerHTML = '<div class="empty-note">Keine BAFU-Lebensraum-Daten im Export. Mit aktivierter Lebensraum-Analyse exportieren.</div>';

  // In-card tabs (VBS Kategorien/Produktiv · Bauzonen/SIA 416/Versiegelung)
  Array.prototype.forEach.call(document.querySelectorAll(".card-tabs"), function (card) {
    var head = card.querySelector(".ctab-head"); if (!head) return;
    head.addEventListener("click", function (e) {
      var b = e.target.closest(".ctab"); if (!b) return;
      var key = b.getAttribute("data-ctab");
      Array.prototype.forEach.call(head.querySelectorAll(".ctab"), function (t) { t.classList.toggle("is-active", t === b); });
      Array.prototype.forEach.call(card.querySelectorAll(".ctab-pane"), function (pane) { pane.hidden = pane.getAttribute("data-pane") !== key; });
    });
  });
  document.getElementById("pill-row").addEventListener("click", function (e) {
    if (e.target.id === "pill-reset") { resetAll(); return; }
    var x = e.target.closest(".pill-x"); if (!x) return;
    var i = parseInt(x.getAttribute("data-i"), 10);
    if (_pillActions[i]) { _pillActions[i].remove(); syncDrawer(); commit(); }
  });

  // ---- Column picker ----
  document.getElementById("cols-menu").innerHTML = COLUMNS.map(function (c) {
    return '<label><input type="checkbox" data-key="' + esc(c.key) + '"' + (c.visible ? " checked" : "") + "> " + esc(c.label) + "</label>";
  }).join("");
  document.getElementById("cols-menu").addEventListener("click", function (e) { e.stopPropagation(); });
  document.getElementById("cols-menu").addEventListener("change", function (e) {
    var key = e.target.getAttribute("data-key");
    if (key) { colByKey[key].visible = e.target.checked; renderTable(); }
  });
  document.getElementById("cols-btn").addEventListener("click", function (e) {
    e.stopPropagation(); document.getElementById("cols-menu").classList.toggle("open");
  });
  document.addEventListener("click", function () { document.getElementById("cols-menu").classList.remove("open"); });

  // ---- Sorting / search / pager ----
  document.getElementById("thead-row").addEventListener("click", function (e) {
    var th = e.target.closest("th"); if (!th) return;
    var key = th.getAttribute("data-key");
    if (state.sort === key) state.dir = -state.dir;
    else { state.sort = key; state.dir = colByKey[key] && colByKey[key].num ? -1 : 1; }
    sortRows(); state.page = 1; renderTable();
  });
  var searchTimer;
  document.getElementById("search").addEventListener("input", function (e) {
    clearTimeout(searchTimer);
    var v = e.target.value;
    searchTimer = setTimeout(function () { state.search = v; commit(); }, 150);
  });
  document.getElementById("prev").addEventListener("click", function () { if (state.page > 1) { state.page--; renderBody(); renderPager(); } });
  document.getElementById("next").addEventListener("click", function () {
    var pages = Math.ceil(state.rows.length / state.pageSize);
    if (state.page < pages) { state.page++; renderBody(); renderPager(); }
  });
  document.getElementById("page-size").addEventListener("change", function (e) {
    state.pageSize = parseInt(e.target.value, 10); state.page = 1; renderBody(); renderPager();
  });

  // ---- Filter panel (single column, capped with a "Alle anzeigen" toggle) ----
  var MAX_FILTER = 8;
  var fExpanded = {};
  function chk(attr, key, label, count, checked) {
    return '<label><input type="checkbox" data-' + attr + '="' + esc(key) + '"' + (checked ? " checked" : "") + '>' +
           '<span class="nm">' + esc(label) + '</span><span class="cnt">' + (count || 0) + '</span></label>';
  }
  function capList(id, arr) {
    var el = document.getElementById(id); if (!el) return;
    var exp = fExpanded[id];
    var html = (exp || arr.length <= MAX_FILTER ? arr : arr.slice(0, MAX_FILTER)).join("");
    if (arr.length > MAX_FILTER)
      html += '<button type="button" class="flink show-all" data-fl="' + id + '">' + (exp ? "Weniger anzeigen" : "Alle anzeigen (" + arr.length + ")") + '</button>';
    el.innerHTML = html;
  }
  function renderExclude() { capList("f-exclude", EXCLUDE_RULES.map(function (r) { return chk("x", r.key, r.label, excludeCounts[r.key], filters.exclude[r.key]); })); }
  function renderCantons() { capList("f-cantons", cantonList.map(function (c) { return chk("c", c, c, cantonCounts[c], filters.cantons[c]); })); }
  function renderArts() { capList("f-arts", artListAll.map(function (a) { return chk("a", a, ART_LABELS[a] || a, artParcelCount[a], filters.arts[a]); })); }
  function renderBauzonen() { capList("f-bauzonen", bauzoneListAll.map(function (z) { return chk("z", z, bzLabel(z), bauzoneParcelCount[z], filters.bauzonen[z]); })); }
  function renderTpf() { capList("f-tpf", tpfList.map(function (t) { return chk("t", t, t, tpfCounts[t], filters.tpf[t]); })); }
  function renderEigentum() { capList("f-eigentum", eigentumList.map(function (e) { return chk("e", e, "Eigentumsart " + e, eigentumCounts[e], filters.eigentum[e]); })); }
  function renderStatus() { capList("f-status", statusList.map(function (s) { return chk("s", s, STATUS_LABELS[s] || s, statusCounts[s], filters.status[s]); })); }
  document.getElementById("cov-with").textContent = fmt(covWith);
  document.getElementById("cov-without").textContent = fmt(covWithout);

  var _rerenderGroup = { "f-exclude": renderExclude, "f-cantons": renderCantons, "f-arts": renderArts, "f-bauzonen": renderBauzonen, "f-tpf": renderTpf, "f-eigentum": renderEigentum, "f-status": renderStatus };
  document.getElementById("filter-panel").addEventListener("click", function (e) {
    var b = e.target.closest(".show-all"); if (!b) return;
    var id = b.getAttribute("data-fl"); fExpanded[id] = !fExpanded[id];
    if (_rerenderGroup[id]) _rerenderGroup[id]();
  });
  function bindChecklist(id, attr, facet) {
    document.getElementById(id).addEventListener("change", function (e) {
      var k = e.target.getAttribute("data-" + attr); if (k == null) return;
      if (e.target.checked) filters[facet][k] = true; else delete filters[facet][k];
      commit();
    });
  }
  bindChecklist("f-exclude", "x", "exclude");
  bindChecklist("f-cantons", "c", "cantons");
  bindChecklist("f-arts", "a", "arts");
  bindChecklist("f-bauzonen", "z", "bauzonen");
  bindChecklist("f-tpf", "t", "tpf");
  bindChecklist("f-eigentum", "e", "eigentum");
  bindChecklist("f-status", "s", "status");
  document.getElementById("f-coverage").addEventListener("change", function (e) { filters.coverage = e.target.value; commit(); });
  document.getElementById("cant-toggle").addEventListener("click", function () {
    if (Object.keys(filters.cantons).length < cantonList.length) cantonList.forEach(function (c) { filters.cantons[c] = true; });
    else filters.cantons = {};
    renderCantons(); commit();
  });
  document.getElementById("art-clear").addEventListener("click", function () { filters.arts = {}; renderArts(); commit(); });
  document.getElementById("bauz-clear").addEventListener("click", function () { filters.bauzonen = {}; renderBauzonen(); commit(); });
  document.getElementById("tpf-clear").addEventListener("click", function () { filters.tpf = {}; renderTpf(); commit(); });
  var frBtn = document.getElementById("f-reset"); if (frBtn) frBtn.addEventListener("click", resetAll);

  // ---- Tabs ----
  var tabBtns = Array.prototype.slice.call(document.querySelectorAll(".tab"));
  function showTab(name) {
    tabBtns.forEach(function (t) { t.classList.toggle("is-active", t.getAttribute("data-tab") === name); });
    ["overview", "quality", "about"].forEach(function (n) {
      var panel = document.getElementById("panel-" + n);
      if (panel) panel.hidden = (n !== name);
    });
  }
  tabBtns.forEach(function (t) { t.addEventListener("click", function () { showTab(t.getAttribute("data-tab")); }); });

  // ---- Filter panel collapse / expand ----
  var appEl = document.getElementById("app");
  document.getElementById("fp-collapse").addEventListener("click", function () { appEl.classList.add("fp-collapsed"); });
  document.getElementById("fp-expand").addEventListener("click", function () { appEl.classList.remove("fp-collapsed"); });
  // Print: render the full filtered set, restore pagination afterwards
  window.addEventListener("beforeprint", function () { printing = true; renderBody(); });
  window.addEventListener("afterprint", function () { printing = false; renderBody(); });

  // ---- Hover info tooltips ----
  var tipEl = document.getElementById("tip");
  function showTip(t) {
    var txt = t.getAttribute("data-tip"); if (!txt) return;
    tipEl.textContent = txt;
    var r = t.getBoundingClientRect(), w = tipEl.offsetWidth, h = tipEl.offsetHeight;
    var top = r.top - h - 8; if (top < 8) top = r.bottom + 8;
    var left = Math.max(8, Math.min(r.left + r.width / 2 - w / 2, window.innerWidth - w - 8));
    tipEl.style.top = top + "px"; tipEl.style.left = left + "px";
    tipEl.classList.add("show");
  }
  function hideTip() { tipEl.classList.remove("show"); }
  document.addEventListener("mouseover", function (e) { var t = e.target.closest("[data-tip]"); if (t) showTip(t); });
  document.addEventListener("mouseout", function (e) { if (e.target.closest("[data-tip]")) hideTip(); });
  document.addEventListener("focusin", function (e) { var t = e.target.closest("[data-tip]"); if (t) showTip(t); });
  document.addEventListener("focusout", hideTip);

  // ---- Download menu (header): offline HTML deliverable + Excel of the table ----
  (function () {
    var btn = document.getElementById("dl-btn"), menu = document.getElementById("dl-menu");
    var titleInput = document.getElementById("dl-title"), hint = document.getElementById("dl-hint");
    if (window.DASHBOARD_TITLE) titleInput.value = window.DASHBOARD_TITLE;
    var titleVal = function () { return (titleInput.value || "BBL Landcover Dashboard").trim(); };
    btn.addEventListener("click", function (e) { e.stopPropagation(); menu.classList.toggle("open"); });
    menu.addEventListener("click", function (e) { e.stopPropagation(); });
    document.addEventListener("click", function () { menu.classList.remove("open"); });
    document.getElementById("dl-html").addEventListener("click", function () {
      var prev = hint.textContent; hint.textContent = "HTML wird erstellt…";
      buildDeliverable(PARCELS, titleVal()).then(function (html) {
        saveBlob(html, "text/html;charset=utf-8", slug(titleVal()) + ".html");
        hint.textContent = prev; menu.classList.remove("open");
      }).catch(function (err) {
        hint.textContent = "HTML-Download benötigt einen Webserver (fetch ist über file:// blockiert). " + err.message;
      });
    });
    document.getElementById("dl-xlsx").addEventListener("click", function () {
      var prev = hint.textContent; hint.textContent = "Excel wird erstellt…";
      loadXlsx().then(function (XLSX) {
        var vis = COLUMNS.filter(function (c) { return c.visible; });
        var aoa = [vis.map(function (c) { return c.label; })];
        state.rows.forEach(function (p) {
          aoa.push(vis.map(function (c) { return c.num ? num(p[c.key]) : (p[c.key] == null ? "" : String(p[c.key])); }));
        });
        var wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(aoa), "Grundstücke");
        XLSX.writeFile(wb, slug(titleVal()) + "-tabelle.xlsx");
        hint.textContent = prev; menu.classList.remove("open");
      }).catch(function (err) { hint.textContent = "Excel-Fehler: " + err.message; });
    });
  })();

  // ---- "Neue Datei": reload to a clean URL → file picker (served builder) ----
  var bn0 = document.getElementById("btn-new");
  if (bn0) bn0.addEventListener("click", function () { location.href = location.pathname; });

  // ---- Area unit toggle (ha / m²) — display only; re-renders every area number ----
  var unitBtns = Array.prototype.slice.call(document.querySelectorAll("#unit-toggle .unit-btn"));
  function syncUnitUI() { unitBtns.forEach(function (b) { b.classList.toggle("is-active", b.getAttribute("data-unit") === areaUnit); }); }
  unitBtns.forEach(function (b) {
    b.addEventListener("click", function () {
      var u = b.getAttribute("data-unit"); if (u === areaUnit) return;
      areaUnit = u;
      try { localStorage.setItem("dashAreaUnit", u); } catch (e) { /* storage may be blocked */ }
      syncUnitUI(); update();
    });
  });
  syncUnitUI();

  // ---- Map: CARTO grey basemap + parcel polygons, poles & clustered ID points ----
  var map = null, mapReady = false, mapFitted = false, refitMap = false, lastRows = [];

  // Pole of inaccessibility (a polygon's "visual center") — ported from @mapbox/polylabel (ISC).
  function _segDistSq(px, py, a, b) {
    var x = a[0], y = a[1], dx = b[0] - x, dy = b[1] - y;
    if (dx !== 0 || dy !== 0) { var t = ((px - x) * dx + (py - y) * dy) / (dx * dx + dy * dy); if (t > 1) { x = b[0]; y = b[1]; } else if (t > 0) { x += dx * t; y += dy * t; } }
    dx = px - x; dy = py - y; return dx * dx + dy * dy;
  }
  function _ptPolyDist(x, y, polygon) {
    var inside = false, minSq = Infinity, r, ring, i, len, j, a, b;
    for (r = 0; r < polygon.length; r++) { ring = polygon[r]; for (i = 0, len = ring.length, j = len - 1; i < len; j = i++) { a = ring[i]; b = ring[j];
      if ((a[1] > y) !== (b[1] > y) && x < ((b[0] - a[0]) * (y - a[1])) / (b[1] - a[1]) + a[0]) inside = !inside;
      minSq = Math.min(minSq, _segDistSq(x, y, a, b)); } }
    return (inside ? 1 : -1) * Math.sqrt(minSq);
  }
  function _mkCell(x, y, h, polygon) { var d = _ptPolyDist(x, y, polygon); return { x: x, y: y, h: h, d: d, max: d + h * Math.SQRT2 }; }
  function _centroidCell(polygon) {
    var area = 0, x = 0, y = 0, ring = polygon[0], i, len, j, a, b, f;
    for (i = 0, len = ring.length, j = len - 1; i < len; j = i++) { a = ring[i]; b = ring[j]; f = a[0] * b[1] - b[0] * a[1]; x += (a[0] + b[0]) * f; y += (a[1] + b[1]) * f; area += f * 3; }
    return area === 0 ? _mkCell(ring[0][0], ring[0][1], 0, polygon) : _mkCell(x / area, y / area, 0, polygon);
  }
  function poleOf(polygon) {
    var ring = polygon && polygon[0]; if (!ring || !ring.length) return null;
    var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity, i, x, y;
    for (i = 0; i < ring.length; i++) { x = ring[i][0]; y = ring[i][1]; if (x < minX) minX = x; if (y < minY) minY = y; if (x > maxX) maxX = x; if (y > maxY) maxY = y; }
    var width = maxX - minX, height = maxY - minY, cellSize = Math.min(width, height);
    if (cellSize === 0) return [minX, minY];
    var prec = Math.max(width, height) / 1000, h = cellSize / 2, heap = [];
    function hpush(c) { heap.push(c); var pos = heap.length - 1; while (pos > 0) { var par = (pos - 1) >> 1; if (heap[par].max >= heap[pos].max) break; var t = heap[par]; heap[par] = heap[pos]; heap[pos] = t; pos = par; } }
    function hpop() { var top = heap[0], last = heap.pop(); if (heap.length) { heap[0] = last; var pos = 0, n = heap.length; for (;;) { var lg = pos, l = 2 * pos + 1, rr = 2 * pos + 2; if (l < n && heap[l].max > heap[lg].max) lg = l; if (rr < n && heap[rr].max > heap[lg].max) lg = rr; if (lg === pos) break; var t = heap[lg]; heap[lg] = heap[pos]; heap[pos] = t; pos = lg; } } return top; }
    for (x = minX; x < maxX; x += cellSize) for (y = minY; y < maxY; y += cellSize) hpush(_mkCell(x + h, y + h, h, polygon));
    var best = _centroidCell(polygon), bbox = _mkCell(minX + width / 2, minY + height / 2, 0, polygon);
    if (bbox.d > best.d) best = bbox;
    while (heap.length) { var cell = hpop(); if (cell.d > best.d) best = cell; if (cell.max - best.d <= prec) continue; h = cell.h / 2;
      hpush(_mkCell(cell.x - h, cell.y - h, h, polygon)); hpush(_mkCell(cell.x + h, cell.y - h, h, polygon)); hpush(_mkCell(cell.x - h, cell.y + h, h, polygon)); hpush(_mkCell(cell.x + h, cell.y + h, h, polygon)); }
    return [best.x, best.y];
  }
  function poleOfGeom(g) {
    if (!g) return null;
    if (g.type === "Polygon") return poleOf(g.coordinates);
    if (g.type === "MultiPolygon") {
      var best = null, bestA = -1;
      g.coordinates.forEach(function (poly) { var ring = poly[0]; if (!ring) return; var mnX = Infinity, mnY = Infinity, mxX = -Infinity, mxY = -Infinity; ring.forEach(function (pt) { if (pt[0] < mnX) mnX = pt[0]; if (pt[1] < mnY) mnY = pt[1]; if (pt[0] > mxX) mxX = pt[0]; if (pt[1] > mxY) mxY = pt[1]; }); var ar = (mxX - mnX) * (mxY - mnY); if (ar > bestA) { bestA = ar; best = poly; } });
      return best ? poleOf(best) : null;
    }
    return null;
  }

  function rowsToFC(rows) {
    return { type: "FeatureCollection", features: rows.filter(function (p) { return p && p._geom; }).map(function (p) {
      return { type: "Feature", geometry: p._geom, properties: { id: p.id || "", ort: p.input_ort || "", egrid: p.egrid || "", area: num(p.parcel_area_m2) } };
    }) };
  }
  function rowsToPointsFC(rows) {
    var out = [];
    rows.forEach(function (p) {
      if (!p || !p._geom) return;
      if (p._pole === undefined) p._pole = poleOfGeom(p._geom); // computed once per parcel, then cached
      if (p._pole) out.push({ type: "Feature", geometry: { type: "Point", coordinates: p._pole }, properties: { id: String(p.id || "") } });
    });
    return { type: "FeatureCollection", features: out };
  }
  function fitMap(fc, animate) {
    var minX = 180, minY = 90, maxX = -180, maxY = -90, any = false;
    function walk(c) { if (typeof c[0] === "number") { if (c[0] < minX) minX = c[0]; if (c[0] > maxX) maxX = c[0]; if (c[1] < minY) minY = c[1]; if (c[1] > maxY) maxY = c[1]; any = true; } else for (var i = 0; i < c.length; i++) walk(c[i]); }
    fc.features.forEach(function (f) { if (f.geometry && f.geometry.coordinates) walk(f.geometry.coordinates); });
    if (any && map) map.fitBounds([[minX, minY], [maxX, maxY]], { padding: 30, animate: !!animate, duration: 600, maxZoom: 16 });
  }
  function renderMap(rows) {
    lastRows = rows;
    if (!mapReady || !map) return;
    var polyFC = rowsToFC(rows);
    var ps = map.getSource("parcels"); if (ps) ps.setData(polyFC);
    var pts = map.getSource("points"); if (pts) pts.setData(rowsToPointsFC(rows));
    // Zoom to the (filtered) results: instant on first load, animated on later filter changes.
    if (polyFC.features.length && (refitMap || !mapFitted)) { fitMap(polyFC, mapFitted); mapFitted = true; }
    refitMap = false;
  }
  // Custom "home" control — zoom to the current (filtered) selection.
  function HomeControl() {}
  HomeControl.prototype.onAdd = function (m) {
    this._map = m;
    var div = document.createElement("div");
    div.className = "maplibregl-ctrl maplibregl-ctrl-group";
    var btn = document.createElement("button");
    btn.type = "button"; btn.className = "map-home"; btn.title = "Auf Auswahl zoomen"; btn.setAttribute("aria-label", "Auf Auswahl zoomen");
    btn.innerHTML = '<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 11.5 12 4l9 7.5"/><path d="M5 10v9h5v-6h4v6h5v-9"/></svg>';
    btn.addEventListener("click", function () { if (lastRows && lastRows.length) fitMap(rowsToFC(lastRows), true); });
    div.appendChild(btn); this._container = div; return div;
  };
  HomeControl.prototype.onRemove = function () { if (this._container && this._container.parentNode) this._container.parentNode.removeChild(this._container); this._map = undefined; };
  function initMap(el) {
    map = new maplibregl.Map({ container: el, style: "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json", center: [8.23, 46.82], zoom: 6.4 });
    map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-right");
    map.addControl(new HomeControl(), "top-right");
    map.on("load", function () {
      map.addSource("parcels", { type: "geojson", data: rowsToFC(lastRows) });
      map.addLayer({ id: "parcels-fill", type: "fill", source: "parcels", paint: { "fill-color": "#6f8aac", "fill-opacity": 0.4 } });
      map.addLayer({ id: "parcels-line", type: "line", source: "parcels", paint: { "line-color": "#3b5a7a", "line-width": 0.7 } });
      map.addLayer({ id: "parcels-hl", type: "line", source: "parcels", filter: ["==", ["get", "id"], selectedParcelId || " "], paint: { "line-color": "#d8232a", "line-width": 2.6 } });
      map.addSource("points", { type: "geojson", data: rowsToPointsFC(lastRows), cluster: true, clusterRadius: 48, clusterMaxZoom: 13 });
      map.addLayer({ id: "clusters", type: "circle", source: "points", filter: ["has", "point_count"],
        paint: { "circle-color": ["step", ["get", "point_count"], "#9db4cc", 25, "#6f8aac", 100, "#3b5a7a"], "circle-radius": ["step", ["get", "point_count"], 14, 25, 18, 100, 24], "circle-stroke-color": "#fff", "circle-stroke-width": 1.5 } });
      map.addLayer({ id: "cluster-count", type: "symbol", source: "points", filter: ["has", "point_count"],
        layout: { "text-field": ["get", "point_count_abbreviated"], "text-font": ["Open Sans Regular"], "text-size": 12 }, paint: { "text-color": "#fff" } });
      map.addLayer({ id: "point", type: "circle", source: "points", filter: ["!", ["has", "point_count"]],
        paint: { "circle-color": "#3b5a7a", "circle-radius": 4, "circle-stroke-color": "#fff", "circle-stroke-width": 1.2 } });
      map.addLayer({ id: "point-label", type: "symbol", source: "points", filter: ["!", ["has", "point_count"]],
        layout: { "text-field": ["get", "id"], "text-font": ["Open Sans Regular"], "text-size": 11, "text-anchor": "bottom", "text-offset": [0, -0.5], "text-optional": true },
        paint: { "text-color": "#1f2937", "text-halo-color": "#fff", "text-halo-width": 1.4 } });
      mapReady = true; mapFitted = false; renderMap(lastRows);
      map.on("click", "parcels-fill", function (e) {
        var f = e.features && e.features[0]; if (!f) return; var pr = f.properties;
        selectParcel(pr.id); // highlight polygon + select & scroll the table row
        new maplibregl.Popup({ closeButton: false }).setLngLat(e.lngLat)
          .setHTML("<strong>" + esc(pr.ort || "—") + "</strong><br>" + esc(pr.id || "") + (pr.egrid ? "<br>" + esc(pr.egrid) : "") + "<br>" + fmtAreaU(pr.area)).addTo(map);
      });
      map.on("click", "clusters", function (e) {
        var f = map.queryRenderedFeatures(e.point, { layers: ["clusters"] })[0]; if (!f) return;
        map.getSource("points").getClusterExpansionZoom(f.properties.cluster_id, function (err, zoom) { if (err) return; map.easeTo({ center: f.geometry.coordinates, zoom: zoom }); });
      });
      ["parcels-fill", "clusters", "point"].forEach(function (lid) {
        map.on("mouseenter", lid, function () { map.getCanvas().style.cursor = "pointer"; });
        map.on("mouseleave", lid, function () { map.getCanvas().style.cursor = ""; });
      });
    });
  }
  var _mapTried = false;
  function ensureMap() {
    var el = document.getElementById("map"); if (!el || _mapTried) return; _mapTried = true;
    if (window.maplibregl) { initMap(el); return; }
    el.innerHTML = '<div class="map-msg">Karte wird geladen…</div>';
    var css = document.createElement("link"); css.rel = "stylesheet"; css.href = "https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.css"; document.head.appendChild(css);
    var s = document.createElement("script"); s.src = "https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.js";
    s.onload = function () { el.innerHTML = ""; initMap(el); };
    s.onerror = function () { el.innerHTML = '<div class="map-msg">Karte benötigt eine Internetverbindung (MapLibre + swisstopo).</div>'; };
    document.head.appendChild(s);
  }

  // ---- Init ----
  var dt0 = document.getElementById("dash-title"); if (dt0 && window.DASHBOARD_TITLE) dt0.textContent = window.DASHBOARD_TITLE;
  var appliedDefaults = readURL();
  syncDrawer();
  if (appliedDefaults) writeURL();   // first (empty) visit → stamp the active defaults into the URL
  update();
  ensureMap();
  } // ── end boot() ──

  // ── Dispatch: embedded data → dashboard; no data → file picker ──
  var __embedded = window.PARCELS || [];
  if (!__embedded.length) {
    initPicker();
  } else {
    if (window.DASHBOARD_TITLE) { try { document.title = window.DASHBOARD_TITLE; } catch (e) {} }
    boot(__embedded);
    var bnE = document.getElementById("btn-new"); if (bnE) bnE.style.display = "none";
  }
})();
